"""Safe local intake and privacy-gate surface."""

from .pipeline import MediaPreparationError, prepare_g1, start_intake, store_transcript
from .storage import CaseMediaStore, MediaStorageError, UnsafeStoragePath
from .types import (
    AudioUpload,
    AuditField,
    CaseHandle,
    ExifChoice,
    ExifDecision,
    ExifFieldSummary,
    ImageFormat,
    ImageUpload,
    IntakeConsents,
    IntakeRequest,
    IntakeSession,
    IntakeStartResult,
    ModelAsset,
    PreparedMedia,
    PrivacyResult,
    PrivacyReview,
    SafeAuditSummary,
    StoredAssetRef,
    StoredImage,
)
from .validation import MAX_AUDIO_SECONDS, MAX_IMAGE_BYTES, PCM_WAV_MEDIA_TYPE, validate_g0

__all__ = [
    "MAX_AUDIO_SECONDS",
    "MAX_IMAGE_BYTES",
    "PCM_WAV_MEDIA_TYPE",
    "AudioUpload",
    "AuditField",
    "CaseHandle",
    "CaseMediaStore",
    "ExifChoice",
    "ExifDecision",
    "ExifFieldSummary",
    "ImageFormat",
    "ImageUpload",
    "IntakeConsents",
    "IntakeRequest",
    "IntakeSession",
    "IntakeStartResult",
    "MediaPreparationError",
    "MediaStorageError",
    "ModelAsset",
    "PreparedMedia",
    "PrivacyResult",
    "PrivacyReview",
    "SafeAuditSummary",
    "StoredAssetRef",
    "StoredImage",
    "UnsafeStoragePath",
    "prepare_g1",
    "start_intake",
    "store_transcript",
    "validate_g0",
]
