"""Public ClaimDone contract surface.

Consumers must import these canonical models instead of defining local copies.
"""

from .base import CONTRACT_VERSION
from .enums import (
    ActorType,
    AllowedTool,
    AuditEventType,
    CaseState,
    CheckpointStatus,
    CounterpartyKnown,
    EvalPriority,
    EvaluationMode,
    EvidenceField,
    EvidenceKind,
    FactStatus,
    GateId,
    GateReasonCode,
    HumanCheckpointId,
    PortalState,
    ReleaseCheckId,
    RequiredClaimField,
    VerificationFieldStatus,
    VerificationState,
)
from .evals import (
    DeterministicEvalExpectation,
    EvalCase,
    EvalExpectation,
    EvalInput,
    ExpectedGateDecision,
    FactExpectation,
    ModelGraderExpectation,
    PortalValueExpectation,
)
from .models import (
    AuditDetail,
    AuditEvent,
    ClaimData,
    ClaimPacket,
    ClaimScope,
    EvidenceFact,
    EvidenceItem,
    FieldProvenance,
    GateDecision,
    PlanStep,
    ProvenanceRef,
    ToolPlan,
    VerificationFieldResult,
    VerificationReport,
)
from .release import (
    HumanCheckpoint,
    ModelGradeResult,
    ReleaseCheck,
    ReleaseDecision,
)
from .state_machine import (
    CASE_TRANSITIONS,
    TERMINAL_CASE_STATES,
    InvalidCaseTransition,
    is_case_transition_allowed,
    validate_case_transition,
)

__all__ = [
    "CASE_TRANSITIONS",
    "CONTRACT_VERSION",
    "TERMINAL_CASE_STATES",
    "ActorType",
    "AllowedTool",
    "AuditDetail",
    "AuditEvent",
    "AuditEventType",
    "CaseState",
    "CheckpointStatus",
    "ClaimData",
    "ClaimPacket",
    "ClaimScope",
    "CounterpartyKnown",
    "DeterministicEvalExpectation",
    "EvalCase",
    "EvalExpectation",
    "EvalInput",
    "EvalPriority",
    "EvaluationMode",
    "EvidenceFact",
    "EvidenceField",
    "EvidenceItem",
    "EvidenceKind",
    "ExpectedGateDecision",
    "FactExpectation",
    "FactStatus",
    "FieldProvenance",
    "GateDecision",
    "GateId",
    "GateReasonCode",
    "HumanCheckpoint",
    "HumanCheckpointId",
    "InvalidCaseTransition",
    "ModelGradeResult",
    "ModelGraderExpectation",
    "PlanStep",
    "PortalState",
    "PortalValueExpectation",
    "ProvenanceRef",
    "ReleaseCheck",
    "ReleaseCheckId",
    "ReleaseDecision",
    "RequiredClaimField",
    "ToolPlan",
    "VerificationFieldResult",
    "VerificationFieldStatus",
    "VerificationReport",
    "VerificationState",
    "is_case_transition_allowed",
    "validate_case_transition",
]
