"""Materialize the exact synthetic image inputs used by INT-002.

The generator has no network or third-party dependency. It writes only below
the repository-owned ``.local/int002-fixtures`` directory and never removes
files. The manifest binds every generated byte by SHA-256.
"""

from __future__ import annotations

import argparse
import binascii
import hashlib
import json
import os
import re
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Final, cast

_SHA256: Final = re.compile(r"^[a-f0-9]{64}$")
_IDENTIFIER: Final = re.compile(r"^[a-z0-9][a-z0-9-]{0,63}$")
_FILENAME: Final = re.compile(r"^[0-9]{2}-synthetic-[a-z0-9-]+\.png$")
_MANIFEST_KEYS: Final = {
    "clarification",
    "fixtureId",
    "images",
    "schemaVersion",
    "statement",
    "synthetic",
}
_IMAGE_KEYS: Final = {
    "baseRgb",
    "filename",
    "height",
    "seed",
    "semanticId",
    "sha256",
    "width",
}
_STATEMENT_KEYS: Final = {"filename", "normalization", "sha256"}
_CLARIFICATION_KEYS: Final = {"answer", "field", "round"}


class FixtureManifestError(ValueError):
    """The committed fixture definition is not closed and canonical."""


@dataclass(frozen=True, slots=True)
class ImageSpec:
    semantic_id: str
    filename: str
    width: int
    height: int
    seed: int
    base_rgb: tuple[int, int, int]
    sha256: str


@dataclass(frozen=True, slots=True)
class FixtureManifest:
    fixture_id: str
    statement_filename: str
    statement_sha256: str
    clarification_field: str
    clarification_round: int
    clarification_answer: str
    images: tuple[ImageSpec, ImageSpec, ImageSpec]


def repository_root() -> Path:
    root = Path(__file__).resolve().parents[1]
    if not (root / "pyproject.toml").is_file() or not (root / "package.json").is_file():
        raise FixtureManifestError("Repository root markers are missing")
    return root


def manifest_path(root: Path | None = None) -> Path:
    return (root or repository_root()) / "fixtures" / "int002" / "manifest.json"


def load_manifest(path: Path) -> FixtureManifest:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise FixtureManifestError("Fixture manifest could not be read") from error
    body = _closed_object(raw, _MANIFEST_KEYS, "manifest")
    if type(body["schemaVersion"]) is not int or body["schemaVersion"] != 1:
        raise FixtureManifestError("Fixture manifest version is invalid")
    if body["synthetic"] is not True:
        raise FixtureManifestError("Fixture manifest version or synthetic marker is invalid")
    fixture_id = _identifier(body["fixtureId"], "fixtureId")

    statement = _closed_object(body["statement"], _STATEMENT_KEYS, "statement")
    if (
        statement["filename"] != "statement.txt"
        or statement["normalization"] != "strip_one_terminal_newline"
    ):
        raise FixtureManifestError("Statement binding is invalid")
    statement_digest = _digest(statement["sha256"], "statement.sha256")

    clarification = _closed_object(
        body["clarification"], _CLARIFICATION_KEYS, "clarification"
    )
    clarification_round = _exact_int(
        clarification["round"],
        "clarification.round",
        minimum=1,
        maximum=1,
    )
    if (
        clarification["field"] != "incident_time"
        or clarification["answer"] != "14:30:00"
    ):
        raise FixtureManifestError("Clarification binding is invalid")

    images_raw = body["images"]
    if not isinstance(images_raw, list) or len(images_raw) != 3:
        raise FixtureManifestError("Fixture manifest requires exactly three images")
    parsed = tuple(_parse_image(item, index) for index, item in enumerate(images_raw, start=1))
    if len({item.semantic_id for item in parsed}) != 3 or len(
        {item.filename for item in parsed}
    ) != 3:
        raise FixtureManifestError("Fixture image identities must be unique")
    images = cast(tuple[ImageSpec, ImageSpec, ImageSpec], parsed)
    return FixtureManifest(
        fixture_id=fixture_id,
        statement_filename=cast(str, statement["filename"]),
        statement_sha256=statement_digest,
        clarification_field=cast(str, clarification["field"]),
        clarification_round=clarification_round,
        clarification_answer=cast(str, clarification["answer"]),
        images=images,
    )


def normalized_statement_bytes(path: Path) -> bytes:
    try:
        raw = path.read_bytes()
    except OSError as error:
        raise FixtureManifestError("Fixture statement could not be read") from error
    if b"\r" in raw or not raw.endswith(b"\n") or raw.endswith(b"\n\n"):
        raise FixtureManifestError("Fixture statement must have one LF terminator")
    normalized = raw[:-1]
    try:
        normalized.decode("utf-8")
    except UnicodeDecodeError as error:
        raise FixtureManifestError("Fixture statement must be UTF-8") from error
    return normalized


def build_png(spec: ImageSpec) -> bytes:
    """Build a small, visibly synthetic RGB PNG with stable uncompressed DEFLATE."""

    scanlines = bytearray()
    for y in range(spec.height):
        scanlines.append(0)
        for x in range(spec.width):
            checker = 28 if ((x // 12) + (y // 8) + spec.seed) % 2 else 0
            diagonal = 44 if (x + spec.seed * 7 - y) % 29 < 3 else 0
            red, green, blue = spec.base_rgb
            scanlines.extend(
                (
                    min(255, red + checker + diagonal),
                    min(255, green + checker // 2),
                    min(255, blue + diagonal // 2),
                )
            )
    ihdr = struct.pack(">IIBBBBB", spec.width, spec.height, 8, 2, 0, 0, 0)
    return b"".join(
        (
            b"\x89PNG\r\n\x1a\n",
            _png_chunk(b"IHDR", ihdr),
            _png_chunk(b"IDAT", _stored_zlib(bytes(scanlines))),
            _png_chunk(b"IEND", b""),
        )
    )


def computed_digests(manifest: FixtureManifest, root: Path) -> dict[str, str]:
    values = {
        image.semantic_id: hashlib.sha256(build_png(image)).hexdigest()
        for image in manifest.images
    }
    statement = normalized_statement_bytes(
        root / "fixtures" / "int002" / manifest.statement_filename
    )
    values["statement"] = hashlib.sha256(statement).hexdigest()
    return values


def materialize(manifest: FixtureManifest, root: Path) -> dict[str, object]:
    output = root / ".local" / "int002-fixtures"
    statement_path = root / "fixtures" / "int002" / manifest.statement_filename
    statement = normalized_statement_bytes(statement_path)
    if hashlib.sha256(statement).hexdigest() != manifest.statement_sha256:
        raise FixtureManifestError("Fixture statement does not match its manifest digest")
    _prepare_output(output, root)
    image_descriptors: list[dict[str, str]] = []
    for spec in manifest.images:
        data = build_png(spec)
        actual = hashlib.sha256(data).hexdigest()
        if actual != spec.sha256:
            raise FixtureManifestError("Generated image does not match its manifest digest")
        target = output / spec.filename
        _write_atomic(target, data)
        image_descriptors.append(
            {
                "path": str(target),
                "semanticId": spec.semantic_id,
                "sha256": actual,
            }
        )
    return {
        "clarificationAnswer": manifest.clarification_answer,
        "clarificationField": manifest.clarification_field,
        "fixtureId": manifest.fixture_id,
        "images": image_descriptors,
        "statementPath": str(statement_path),
    }


def check_materialized(manifest: FixtureManifest, root: Path) -> dict[str, object]:
    output = root / ".local" / "int002-fixtures"
    _require_safe_existing_output(output, root)
    expected_names = {spec.filename for spec in manifest.images}
    try:
        actual_names = {item.name for item in output.iterdir()}
    except OSError as error:
        raise FixtureManifestError("Generated fixture directory could not be read") from error
    if actual_names != expected_names:
        raise FixtureManifestError(
            "Generated fixture directory must contain exactly the manifest-bound files"
        )
    statement_path = root / "fixtures" / "int002" / manifest.statement_filename
    statement = normalized_statement_bytes(statement_path)
    if hashlib.sha256(statement).hexdigest() != manifest.statement_sha256:
        raise FixtureManifestError("Fixture statement does not match its manifest digest")
    for spec in manifest.images:
        target = output / spec.filename
        if target.is_symlink():
            raise FixtureManifestError("Generated fixture path must not be a symlink")
        try:
            data = target.read_bytes()
        except OSError as error:
            raise FixtureManifestError("Generated fixture image is missing") from error
        if hashlib.sha256(data).hexdigest() != spec.sha256 or data != build_png(spec):
            raise FixtureManifestError("Generated fixture image is not reproducible")
    return materialized_descriptor(manifest, root)


def materialized_descriptor(manifest: FixtureManifest, root: Path) -> dict[str, object]:
    output = root / ".local" / "int002-fixtures"
    return {
        "clarificationAnswer": manifest.clarification_answer,
        "clarificationField": manifest.clarification_field,
        "fixtureId": manifest.fixture_id,
        "images": [
            {
                "path": str(output / spec.filename),
                "semanticId": spec.semantic_id,
                "sha256": spec.sha256,
            }
            for spec in manifest.images
        ],
        "statementPath": str(
            root / "fixtures" / "int002" / manifest.statement_filename
        ),
    }


def _parse_image(value: object, index: int) -> ImageSpec:
    body = _closed_object(value, _IMAGE_KEYS, f"images[{index - 1}]")
    width = _exact_int(body["width"], "width", minimum=32, maximum=256)
    height = _exact_int(body["height"], "height", minimum=32, maximum=256)
    seed = _exact_int(body["seed"], "seed", minimum=1, maximum=3)
    if seed != index:
        raise FixtureManifestError("Fixture image seed must match its one-based position")
    rgb_raw = body["baseRgb"]
    if not isinstance(rgb_raw, list) or len(rgb_raw) != 3:
        raise FixtureManifestError("baseRgb must contain exactly three channels")
    rgb = tuple(_exact_int(channel, "baseRgb", minimum=0, maximum=180) for channel in rgb_raw)
    return ImageSpec(
        semantic_id=_identifier(body["semanticId"], "semanticId"),
        filename=_filename(body["filename"]),
        width=width,
        height=height,
        seed=seed,
        base_rgb=cast(tuple[int, int, int], rgb),
        sha256=_digest(body["sha256"], "sha256"),
    )


def _closed_object(
    value: object, expected_keys: set[str], label: str
) -> dict[str, object]:
    if not isinstance(value, dict) or set(value) != expected_keys:
        raise FixtureManifestError(f"{label} must contain only its canonical fields")
    if any(type(key) is not str for key in value):
        raise FixtureManifestError(f"{label} keys must be strings")
    return cast(dict[str, object], value)


def _identifier(value: object, label: str) -> str:
    if type(value) is not str or _IDENTIFIER.fullmatch(value) is None:
        raise FixtureManifestError(f"{label} is invalid")
    return value


def _filename(value: object) -> str:
    if type(value) is not str or _FILENAME.fullmatch(value) is None:
        raise FixtureManifestError("Fixture filename is invalid")
    return value


def _digest(value: object, label: str) -> str:
    if type(value) is not str or _SHA256.fullmatch(value) is None:
        raise FixtureManifestError(f"{label} must be a lowercase SHA-256")
    return value


def _exact_int(value: object, label: str, *, minimum: int, maximum: int) -> int:
    if type(value) is not int or not minimum <= value <= maximum:
        raise FixtureManifestError(f"{label} is outside its closed integer range")
    return value


def _png_chunk(kind: bytes, payload: bytes) -> bytes:
    checksum = binascii.crc32(kind + payload) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + kind + payload + struct.pack(">I", checksum)


def _stored_zlib(payload: bytes) -> bytes:
    if len(payload) > 65_535:
        raise FixtureManifestError("Synthetic fixture scanline payload is unexpectedly large")
    length = len(payload)
    nlength = length ^ 0xFFFF
    return b"".join(
        (
            b"\x78\x01",
            b"\x01",
            struct.pack("<HH", length, nlength),
            payload,
            struct.pack(">I", _adler32(payload)),
        )
    )


def _adler32(payload: bytes) -> int:
    first = 1
    second = 0
    for byte in payload:
        first = (first + byte) % 65_521
        second = (second + first) % 65_521
    return (second << 16) | first


def _prepare_output(output: Path, root: Path) -> None:
    local = root / ".local"
    if local.exists() and local.is_symlink():
        raise FixtureManifestError("Repository .local directory must not be a symlink")
    local.mkdir(mode=0o700, exist_ok=True)
    if output.exists() and output.is_symlink():
        raise FixtureManifestError("Fixture output directory must not be a symlink")
    output.mkdir(mode=0o700, exist_ok=True)
    _require_safe_existing_output(output, root)


def _require_safe_existing_output(output: Path, root: Path) -> None:
    expected = (root / ".local" / "int002-fixtures").resolve()
    if output.resolve() != expected or root.resolve() not in expected.parents:
        raise FixtureManifestError("Fixture output escaped the repository-local boundary")
    if not output.is_dir() or output.is_symlink():
        raise FixtureManifestError("Fixture output must be a real directory")


def _write_atomic(path: Path, data: bytes) -> None:
    if path.exists() and path.is_symlink():
        raise FixtureManifestError("Generated fixture path must not be a symlink")
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    if temporary.exists() and temporary.is_symlink():
        raise FixtureManifestError("Generated fixture temporary path is unsafe")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    descriptor: int | None = None
    created_temporary = False
    try:
        descriptor = os.open(temporary, flags, 0o600)
        created_temporary = True
        with os.fdopen(descriptor, "wb") as stream:
            descriptor = None
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except FileExistsError as error:
        raise FixtureManifestError("Generated fixture temporary path is unsafe") from error
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if created_temporary and temporary.exists() and not temporary.is_symlink():
            temporary.unlink()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Verify existing generated files")
    mode.add_argument(
        "--print-digests",
        action="store_true",
        help="Print computed public fixture digests without writing files",
    )
    parser.add_argument("--json", action="store_true", help="Emit a JSON descriptor")
    return parser


def main() -> int:
    args = _parser().parse_args()
    root = repository_root()
    manifest = load_manifest(manifest_path(root))
    if args.print_digests:
        result: object = computed_digests(manifest, root)
    elif args.check:
        result = check_materialized(manifest, root)
    else:
        result = materialize(manifest, root)
    if args.json or args.print_digests:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print(f"INT-002 fixture ready: {manifest.fixture_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
